version: "3.8"

volumes:
    pg-volume:
      driver: local
      external: False
      name: pg-volume

services:
  pg-database:
    image:  "postgres:9.6.18"
    container_name: "pg-database"
    ports:
      - "5432:5432"
    volumes:
      - type: volume
        source: pg-volume
        target: /var/lib/postgresql/data
    env_file:
      - ./env_var

  backend-recipe:
    build: .
    image: "backend-recipe:${VERSION}"
    container_name: "backend-recipe"
    env_file:
      - ./env_var
    ports:
      - "5000:5000"
    depends_on:
      - pg-database
