version: "3.8"

volumes:
    pg-volume:
      driver: local
      external: False
      name: pg-volume

services:
  pg-database:
    image:  "postgres:9.6.18"
    container_name: "pg-database"
    ports:
      - "8080:5432"
    volumes:
      - type: volume
        source: pg-volume
        target: /var/lib/postgresql/data
    env_file:
      - ./pg_env_var

  backend-recipe:
    build: .
    container_name: "backend-recipe"
    env_file:
      - ./pg_env_var
    ports:
      - "8000:8000"
    depends_on:
      - pg-database
